export const GET_DATA_REQUEST = "GET_DATA_REQUEST";
export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS";
export const GET_DATA_FAILURE = "GET_DATA_FAILURE";

export const ADD_DATA_REQUEST =  "ADD_DATA_REQUEST";
export const ADD_DATA_SUCCESS =  "ADD_DATA_SUCCESS";
export const ADD_DATA_FAILURE =  "ADD_DATA_FAILURE ";

export const EDIT_DATA_REQUEST = "EDIT_DATA_REQUEST";
export const EDIT_DATA_SUCCESS = "EDIT_DATA_SUCCESS";
export const EDIT_DATA_FAILURE = "EDIT_DATA_FAILURE";

export const DELETE_DATA_REQUEST = "DELETE_DATA_REQUEST";
export const DELETE_DATA_SUCCESS = "DELETE_DATA_SUCCESS";
export const DELETE_DATA_FAILURE = "DELETE_DATA_FAILURE";




export const USER_DATA_REQUEST =  "USER_DATA_REQUEST";
export const USER_DATA_SUCCESS =  "USER_DATA_SUCCESS";
export const USER_DATA_FAILURE =  "USER_DATA_FAILURE ";




export const MYPOST_DATA_REQUEST =  "MYPOST_DATA_REQUEST";
export const MYPOST_DATA_SUCCESS =  "MYPOST_DATA_SUCCESS";
export const MYPOST_DATA_FAILURE =  "MYPOST_DATA_FAILURE ";



export const SingleUserProfile_DATA_REQUEST =  "SingleUserProfile_DATA_REQUEST";
export const SingleUserProfile_DATA_SUCCESS =  "SingleUserProfile_DATA_SUCCESS";
export const SingleUserProfile_DATA_FAILURE =  "SingleUserProfile_DATA_FAILURE ";



export const AllREEL_DATA_REQUEST =  "AllREEL_DATA_REQUEST";
export const AllREEL_DATA_SUCCESS =  "AllREEL_DATA_SUCCESS";
export const AllREEL_DATA_FAILURE =  "AllREEL_DATA_FAILURE ";
